### PR TITLE
Access other users profile

### LINKED ISSUE #40: We can't access other users profile yet

### PR DESCRIPTION
**Pull request by pde-bakk**
now, in the #chat section, you can click on a users name/profile picture and it'll direct you to view their profile!

closes #40

### CODE REVIEW

**Comment by SaltyMilk** [comment]
I can't build this. Tried multiple times, docker system prune -a between still doesn't work.
Last log msg : 
```
web_1    | Bundle complete! 19 Gemfile dependencies, 84 gems now installed.
web_1    | Use `bundle info [gemname]` to see where a bundled gem is installed.
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 3.71s.
web_1    | Dropped database 'db/development'
```
From what I see in the logs it seems to drop the db multiples times than recreate it migrate, redrop it etc and then the server completly freeze. When I try to db:create inside it the command freezes forever

**Comment by pde-bakk** [comment]
> I can't build this. Tried multiple times, docker system prune -a between still doesn't work.
> Last log msg :
> 
> ```
> web_1    | Bundle complete! 19 Gemfile dependencies, 84 gems now installed.
> web_1    | Use `bundle info [gemname]` to see where a bundled gem is installed.
> yarn install v1.22.5
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 3.71s.
> web_1    | Dropped database 'db/development'
> ```
> 
> From what I see in the logs it seems to drop the db multiples times than recreate it migrate, redrop it etc and then the server completly freeze. When I try to db:create inside it the command freezes forever

I left the ENTRYPOINT statement in the Dockerfile but not the CMD one, so it just kept running the migrations and then exiting and restarting.

Fixed now

**Comment by SaltyMilk** [comment]
Looks good, seems ready for merge.
A little bugs though on game: 
-black screen on games (but when going back to home then -> #game and joining the game it works) 
-the ball sometimes go through the paddle

**Comment by pde-bakk** [comment]
Good point, I believe those bugs have been fixed on the Ladder Pull request

**Pull request merged**
